### ISSUE TITLE
[NEXUS-28979] Maven Group has inappropriate fields in UI (create and edit)

### ISSUE THREAD

**Issue by Vampire** [sonatype/nexus-public#137]
Nexus version OSS 3.34.0

Maven Group displays all the "Maven 2" variables (Version policy, Layout policy, Content Disposition) on creation and edit typical of proxy and hosted repositories.

This is errant, at least Version policy and Layout policy (Content Disposition I believe also but not 100% sure) are not used by group, they use the individual member settings.

![image](https://github.com/sonatype/nexus-public/assets/325196/2983f3ac-58c1-4fa5-a01b-364d128b9f8f)

**Comment by nblair** [comment]
I'd like to learn a little more about your goals and needs - is there another forum we can discuss? I'm concerned that this approach to replicate a mass number of tickets is going to overwhelm our ability to review other issues here in a timely fashion.

**Comment by Vampire** [comment]
Oh, sorry, then I probably misunderstood.
I thought we should re-report here what we still want to keep tracked.
But I'm done with my created and the one voted/watched issue anyway.
Sorry for the noise then.

**Comment by nblair** [comment]
No worries! Thanks for responding. I saw the list climbing quickly and wasn't sure if there was some automation involved.

It will take us some time to review the list. In the interim, it looks like you're reporting all against old versions of the product released in 2021.

Have you taken a look at the latest releases per https://help.sonatype.com/repomanager3/product-information/release-notes? I wonder if some of the behaviors you described have already been addressed in recent versions. 

Having a fresh bug report against a current version, along with answers to the questions listed in our issue template will result in the best chances for us to help.

Thanks!

**Comment by Vampire** [comment]
Unfortunately, we do not have a newer version installed yet, so I was not able to re-tests.
Besides that I did not have the time to retest all the issues just due to the re-report.
But I mainly assumed nothing happened as the issues were almost all untouched.
I re-checked some of the doc issues that referred to online URLs and all I checked were also still the same.
